apiVersion: v1
kind: Service
metadata:
  namespace: unaffected
  name: nginx-service2
spec:
  selector:
    app: nginx2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
