apiVersion: v1
kind: Service
metadata:
  namespace: target
  name: nginx-service1
spec:
  selector:
    app: nginx1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
